server:
  port: 2001

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
